["Leica M6"]
"Exif.Image.Make" = "Leica"
"Exif.Image.Model" = "M6"

["Mamiya RB67"]
"Exif.Image.Make" = "Mamiya"
"Exif.Image.Model" = "RB67"

["Nikon F100"]
"Exif.Image.Make" = "Nikon"
"Exif.Image.Model" = "F100"

["Widelux"]
"Exif.Image.Make" = "Widelux"
"Exif.Image.Model" = "F7"

["Weirdocam"]
"Exif.Image.Make" = "Weirdocam"
"Exif.Image.Model" = "T1"
