["Leica M6"]
"Exif.Image.Make" = "Leica"
"Exif.Image.Model" = "Leica M6"

["Mamiya RB67"]
"Exif.Image.Make" = "Mamiya"
"Exif.Image.Model" = "Mamiya RB67"

["Nikon F100"]
"Exif.Image.Make" = "Nikon"
"Exif.Image.Model" = "Nikon F100"

["Widelux"]
"Exif.Image.Make" = "Widelux"
"Exif.Image.Model" = "Widelux F7"

["Nikonos V"]
"Exif.Image.Make" = "Nikon"
"Exif.Image.Model" = "Nikon Nikonos V"
