tap "homebrew/bundle"
brew "ansible"
brew "exiv2"
brew "helix"
brew "hugo"
brew "imagemagick"
brew "jpeg-xl"
brew "jq"
brew "magic-wormhole"
brew "markdown-oxide"
brew "marksman"
brew "mas"
brew "python"
brew "starship"
brew "yt-dlp"
cask "1password"
cask "1password-cli"
cask "aerospace"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "ghostty"
cask "hazel"
mas "1Password for Safari", id: 1569813296
mas "Better", id: 1121192229
mas "Gifski", id: 1351639930
mas "iA Writer", id: 775737590
mas "Paprika Recipe Manager 3", id: 1303222628
mas "PCalc", id: 403504866
mas "Tailscale", id: 1475387142
